// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 20250407-esp32c2x-128115

#ifndef _20250407_ESP32C2X_128115_UI_H
#define _20250407_ESP32C2X_128115_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label1;
void ui_event_background(lv_event_t * e);
extern lv_obj_t * ui_background;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

// SCREEN: ui_working
void ui_working_screen_init(void);
extern lv_obj_t * ui_working;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Bar1;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Label4;
// CUSTOM VARIABLES

// SCREEN: ui_time
void ui_time_screen_init(void);
extern lv_obj_t * ui_time;
void ui_event_Roller1(lv_event_t * e);
extern lv_obj_t * ui_Roller1;
extern lv_obj_t * ui_min;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_back_png);    // assets/back.png
LV_IMG_DECLARE(ui_img_1kaorou_png);    // assets/1kaorou.png
LV_IMG_DECLARE(ui_img_2kaoji_png);    // assets/2kaoji.png
LV_IMG_DECLARE(ui_img_3danta_png);    // assets/3danta.png
LV_IMG_DECLARE(ui_img_4pisa_png);    // assets/4pisa.png
LV_IMG_DECLARE(ui_img_5liupai_png);    // assets/5liupai.png
LV_IMG_DECLARE(ui_img_6shutiao_png);    // assets/6shutiao.png
LV_IMG_DECLARE(ui_img_1611000061);    // assets/时间.png
LV_IMG_DECLARE(ui_img_307400400);    // assets/开始.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
