// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 20250407-esp32c2x-128115

#include "../ui.h"
int options_max_num=15;//索引  从0 开始  下面改，这个数字也得改
 char * options[] = {"15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30"};
 int  options2[]={15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30}; 
void ui_time_screen_init(void)
{
    ui_time = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_time, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Roller1 = lv_roller_create(ui_time);
    lv_roller_set_options(ui_Roller1, "15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30",
                          LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_Roller1, 80);
    lv_obj_set_width(ui_Roller1, LV_SIZE_CONTENT);   /// 40
    lv_obj_set_x(ui_Roller1, 0);
    lv_obj_set_y(ui_Roller1, 0);
    lv_obj_set_align(ui_Roller1, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0xE64500), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Roller1, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_min = lv_label_create(ui_time);
    lv_obj_set_width(ui_min, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_min, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_min, 42);
    lv_obj_set_y(ui_min, 0);
    lv_obj_set_align(ui_min, LV_ALIGN_CENTER);
    lv_label_set_text(ui_min, "min.");

    lv_obj_add_event_cb(ui_Roller1, ui_event_Roller1, LV_EVENT_ALL, NULL);

}
