// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: 20250407-esp32c2x-128115

#include "../ui.h"
// 声明全局变量来存储进度条的值  
static int bar_value = 0;  
 int selected_index=0;
 extern  char * options[];
 extern  int options2[];
 extern int HF_ui_screen_id;
  int HF_number=15;//最初
// 定时器回调函数，用于更新进度条的值  
lv_timer_t * bar_time=NULL;
extern  void  bsp_display_backlight_on(void);
static void HF_start(lv_timer_t * timer)  //晚开背光
{
    static int time_1s=0;
    static bool HF1111=true;
    time_1s++;
    if(HF1111&&(time_1s>2))
    {
        HF1111=false;
        bsp_display_backlight_on();
    }

}
static void bar_update_cb(lv_timer_t * timer)  
{  
    
 
    
    if(HF_ui_screen_id==3)
    {
       
       
        
        // 每次调用时增加进度条的值（可根据需要调整增量）  
        int i=options2[selected_index];
        
        // bar_value += 5;
        bar_value =bar_value+(100/i);
    
        // 若值达到或超过100，则重置为0（对于对称模式，您可能希望设置为某个最大值而非100）  
        if(bar_value >= 100) {  
        // lv_timer_pause(bar_time);
        bar_value = 0;  
         HF_ui_screen_id=1;
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_Screen1_screen_init);
        }  
        //current_value
        // 更新进度条显示  
        
        lv_bar_set_value(ui_Bar1, bar_value, LV_ANIM_ON); // 启用动画效果  
        

        
        char num_str[16]={0}; // 对于32位整数来说，10个字符足够（包括负号和空字符）  
        
        //暂时不用了，不能和进度条反向同步
        // 使用snprintf将整数转换为字符串  
        // HF_number=(bar_value*i)/100;
        // snprintf(num_str, sizeof(num_str), "%d", bar_value);  
        
       
        // _ui_label_set_property(ui_Label1, _UI_LABEL_PROPERTY_TEXT, num_str);
    }
    else
    {
      bar_value = 0;  
      lv_bar_set_value(ui_Bar1, 0, LV_ANIM_ON); // 启用动画效果    
    }
}  
void ui_working_screen_init(void)
{
    ui_working = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_working, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Spinner1 = lv_spinner_create(ui_working, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 128);
    lv_obj_set_height(ui_Spinner1, 128);
    lv_obj_set_x(ui_Spinner1, 0);
    lv_obj_set_y(ui_Spinner1, 6);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Spinner1, lv_color_hex(0xE64500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Spinner1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Spinner1, 5, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_working);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 2);
    lv_obj_set_y(ui_Label2, -34);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "working");

    ui_Label3 = lv_label_create(ui_working);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, -14);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "15");

    ui_Bar1 = lv_bar_create(ui_working);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 80);
    lv_obj_set_height(ui_Bar1, 5);
    lv_obj_set_x(ui_Bar1, 1);
    lv_obj_set_y(ui_Bar1, 6);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0xE64500), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_working);
    lv_obj_set_width(ui_Button5, 20);
    lv_obj_set_height(ui_Button5, 20);
    lv_obj_set_x(ui_Button5, 1);
    lv_obj_set_y(ui_Button5, 29);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xE64500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_working);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 0);
    lv_obj_set_y(ui_Label4, 28);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "S");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
   // lv_obj_set_style_transform_angle(ui_Label4, 922, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button5, ui_event_Button5, LV_EVENT_ALL, NULL);

    bar_time=lv_timer_create(bar_update_cb, 1000, NULL); // 每秒调用一次bar_update_cb函数
    bar_time=lv_timer_create(HF_start, 100, NULL); // 每秒调用一次bar_update_cb函数

}
