/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_OUT2_FILES           56
#define MMAP_OUT2_CHECKSUM        0x1DF0

enum MMAP_OUT2_LISTS {
    MMAP_OUT2_FRAME_000_SQOI = 0,        /*!< frame_000.sqoi */
    MMAP_OUT2_FRAME_001_SQOI = 1,        /*!< frame_001.sqoi */
    MMAP_OUT2_FRAME_002_SQOI = 2,        /*!< frame_002.sqoi */
    MMAP_OUT2_FRAME_003_SQOI = 3,        /*!< frame_003.sqoi */
    MMAP_OUT2_FRAME_004_SQOI = 4,        /*!< frame_004.sqoi */
    MMAP_OUT2_FRAME_005_SQOI = 5,        /*!< frame_005.sqoi */
    MMAP_OUT2_FRAME_006_SQOI = 6,        /*!< frame_006.sqoi */
    MMAP_OUT2_FRAME_007_SQOI = 7,        /*!< frame_007.sqoi */
    MMAP_OUT2_FRAME_008_SQOI = 8,        /*!< frame_008.sqoi */
    MMAP_OUT2_FRAME_009_SQOI = 9,        /*!< frame_009.sqoi */
    MMAP_OUT2_FRAME_010_SQOI = 10,        /*!< frame_010.sqoi */
    MMAP_OUT2_FRAME_011_SQOI = 11,        /*!< frame_011.sqoi */
    MMAP_OUT2_FRAME_012_SQOI = 12,        /*!< frame_012.sqoi */
    MMAP_OUT2_FRAME_013_SQOI = 13,        /*!< frame_013.sqoi */
    MMAP_OUT2_FRAME_014_SQOI = 14,        /*!< frame_014.sqoi */
    MMAP_OUT2_FRAME_015_SQOI = 15,        /*!< frame_015.sqoi */
    MMAP_OUT2_FRAME_016_SQOI = 16,        /*!< frame_016.sqoi */
    MMAP_OUT2_FRAME_017_SQOI = 17,        /*!< frame_017.sqoi */
    MMAP_OUT2_FRAME_018_SQOI = 18,        /*!< frame_018.sqoi */
    MMAP_OUT2_FRAME_019_SQOI = 19,        /*!< frame_019.sqoi */
    MMAP_OUT2_FRAME_020_SQOI = 20,        /*!< frame_020.sqoi */
    MMAP_OUT2_FRAME_021_SQOI = 21,        /*!< frame_021.sqoi */
    MMAP_OUT2_FRAME_022_SQOI = 22,        /*!< frame_022.sqoi */
    MMAP_OUT2_FRAME_023_SQOI = 23,        /*!< frame_023.sqoi */
    MMAP_OUT2_FRAME_024_SQOI = 24,        /*!< frame_024.sqoi */
    MMAP_OUT2_FRAME_025_SQOI = 25,        /*!< frame_025.sqoi */
    MMAP_OUT2_FRAME_026_SQOI = 26,        /*!< frame_026.sqoi */
    MMAP_OUT2_FRAME_027_SQOI = 27,        /*!< frame_027.sqoi */
    MMAP_OUT2_FRAME_028_SQOI = 28,        /*!< frame_028.sqoi */
    MMAP_OUT2_FRAME_029_SQOI = 29,        /*!< frame_029.sqoi */
    MMAP_OUT2_FRAME_030_SQOI = 30,        /*!< frame_030.sqoi */
    MMAP_OUT2_FRAME_031_SQOI = 31,        /*!< frame_031.sqoi */
    MMAP_OUT2_FRAME_032_SQOI = 32,        /*!< frame_032.sqoi */
    MMAP_OUT2_FRAME_033_SQOI = 33,        /*!< frame_033.sqoi */
    MMAP_OUT2_FRAME_034_SQOI = 34,        /*!< frame_034.sqoi */
    MMAP_OUT2_FRAME_035_SQOI = 35,        /*!< frame_035.sqoi */
    MMAP_OUT2_FRAME_036_SQOI = 36,        /*!< frame_036.sqoi */
    MMAP_OUT2_FRAME_037_SQOI = 37,        /*!< frame_037.sqoi */
    MMAP_OUT2_FRAME_038_SQOI = 38,        /*!< frame_038.sqoi */
    MMAP_OUT2_FRAME_039_SQOI = 39,        /*!< frame_039.sqoi */
    MMAP_OUT2_FRAME_040_SQOI = 40,        /*!< frame_040.sqoi */
    MMAP_OUT2_FRAME_041_SQOI = 41,        /*!< frame_041.sqoi */
    MMAP_OUT2_FRAME_042_SQOI = 42,        /*!< frame_042.sqoi */
    MMAP_OUT2_FRAME_043_SQOI = 43,        /*!< frame_043.sqoi */
    MMAP_OUT2_FRAME_044_SQOI = 44,        /*!< frame_044.sqoi */
    MMAP_OUT2_FRAME_045_SQOI = 45,        /*!< frame_045.sqoi */
    MMAP_OUT2_FRAME_046_SQOI = 46,        /*!< frame_046.sqoi */
    MMAP_OUT2_FRAME_047_SQOI = 47,        /*!< frame_047.sqoi */
    MMAP_OUT2_FRAME_048_SQOI = 48,        /*!< frame_048.sqoi */
    MMAP_OUT2_FRAME_049_SQOI = 49,        /*!< frame_049.sqoi */
    MMAP_OUT2_FRAME_050_SQOI = 50,        /*!< frame_050.sqoi */
    MMAP_OUT2_FRAME_051_SQOI = 51,        /*!< frame_051.sqoi */
    MMAP_OUT2_FRAME_052_SQOI = 52,        /*!< frame_052.sqoi */
    MMAP_OUT2_FRAME_053_SQOI = 53,        /*!< frame_053.sqoi */
    MMAP_OUT2_FRAME_054_SQOI = 54,        /*!< frame_054.sqoi */
    MMAP_OUT2_FRAME_055_SQOI = 55,        /*!< frame_055.sqoi */
};
